### PR TITLE
Added Community Contribution

### PR DESCRIPTION
**Pull request by LanceALaughlin**

### CODE REVIEW

**Comment by LanceALaughlin** [comment]
I also made the whole "Fork me on Github" a link...I initially thought the link was non-existent because I hovered over fork me and it took me a second to realize that only Github was a link. I just figured it was a bit more user friendly...fell free to disagree.

I planned on make it a separate pull request but it seemed to update this pull request when I pushed my new commit to my repo.

**Comment by decause** [comment]
:+1: 

Those all look good to me @ExplosiveHippo. 

Have you heard of Gitflow before? There is a way for you to create "feature" branches, and send pull requests from each of those, if you needed to segregate commits :)

Check out http://nvie.com/posts/a-successful-git-branching-model/ for more details

**Comment by ralphbean** [comment]
This fixes #49.

**Comment by LanceALaughlin** [comment]
@decause I've heard of the word but haven't used it in practice. Thanks! I'll definitely read up on it.

**Pull request merged**
