### PR TITLE
Added Community Contribution 0

### PR DESCRIPTION
**Pull request by citruspi**

### CODE REVIEW

**Comment by decause** [comment]
Technically, you're 2 minutes late... :clock12: 

Also, I'm getting a 404 for the link in commcont1. Fix and I'll merge.

**Comment by decause** [comment]
I understand that you'd appreciate a zero index, but that is not what everyone else is using... change to `commcont1`

Also, I'm still getting a 404 on your post...

**Comment by decause** [comment]
@citruspi this still says `commcont0` and there is an extra line at the bottom of the file.

plzfix

**Comment by citruspi** [comment]
@decause,

Sorry, this was actually just a link to Community Contribution 1 which was named `commcont1` in my most recent pull request - this pull request is no longer valid.

I simply forgot to close it.

&mdash; @citruspi

**Pull request closed without merging**
