### PR TITLE
Fixing Yaml

### PR DESCRIPTION
**Pull request by Pharas**
Seeing if I cant fix the rss feed for my blog and added the meetup post

### CODE REVIEW

**Comment by decause** [comment]
@Pharas <code>git pull</code> and then push again to your repo. Looks like you are out of sync.

**Comment by Pharas** [comment]
I have synched my repo

**Comment by msoucy** [comment]
Your repository says otherwise.

```
git remote add upstream git@github.com:decause/advfoss.git
git checkout master
git pull upstream master --rebase
git push origin master
```

Try that?

**Comment by decause** [comment]
@Pharas 

what @msoucy said.

**Comment by msoucy** [comment]
That didn't fix it...

**Pull request closed without merging**
